name: diagvibsix
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit>=10.1
  - imageio>=2.8.0
  - matplotlib>=3.3.0
  - numpy>=1.19.0
  - python>=3.7.0
  - pytorch>=1.6.0
  - pyyaml>=5.3.0
  - scikit-image>=0.17.0
  - scipy>=1.5.0
  - torchvision>=0.7.0
  - tqdm>=4.49.0
  - yaml>=0.2.5
