{
    'method': 'ResNet18Trainer',
    'num_epochs': 30,
    'mbs': 64,
    'optimizer': 'adam',
    'lr': 0.0002,
    'adam_b1': 0.9,
    'adam_b2': 0.999,
    'num_workers': 4,
    'results_path': './tmp/results'
}
